import type { BoundaryCorner, AuditRecord } from '../../../../types';

/** Test farm in Rufiji District, Pwani Region - ~-7.47°N, 39.18°E */
export const TEST_CORNERS: BoundaryCorner[] = [
  {
    lat: -7.470123,
    lon: 39.180456,
    accuracy: 8.5,
    timestamp: '2025-03-10T09:23:15Z',
    sequence: 1,
  },
  {
    lat: -7.470234,
    lon: 39.181123,
    accuracy: 7.2,
    timestamp: '2025-03-10T09:24:30Z',
    sequence: 2,
  },
  {
    lat: -7.471001,
    lon: 39.180987,
    accuracy: 9.1,
    timestamp: '2025-03-10T09:25:45Z',
    sequence: 3,
  },
  {
    lat: -7.47089,
    lon: 39.180321,
    accuracy: 6.8,
    timestamp: '2025-03-10T09:27:00Z',
    sequence: 4,
  },
];

export const VALID_FARM_AUDIT: AuditRecord = {
  id: 'test-audit-1',
  businessName: "John Mchaina's Farm",
  location: {
    latitude: -7.4705,
    longitude: 39.1806,
    accuracy: 7.5,
    timestamp: Date.now() - 60000,
  },
  status: 'pending',
  createdAt: new Date().toISOString(),
  images: [],
  notes: '',
  type: 'farm',
  farmData: {
    farmId: 'test-farm-1',
    auditorId: 'Grace Kimaro',
    auditDate: new Date().toISOString(),
    region: 'Pwani',
    district: 'Rufiji',
    ward: 'Bungu',
    village: 'Bungu Village',
    subvillage: '',
    landmark: '',
    boundaryCorners: TEST_CORNERS,
    farmerFirstName: 'John',
    farmerLastName: 'Mchaina',
    primaryPhone: '+255712345678',
    gender: 'Male',
    ageRange: '36-45',
    householdSize: '4',
    experienceYears: '10',
    education: 'Primary',
    farmerType: 'Smallholder',
    primaryOccupation: 'Farming',
    farmSize: '2.5',
    farmSizeUnit: 'Hectares',
    cultivatedArea: '2',
    landTenure: 'Own with title',
    soilType: 'Loam',
    topography: 'Flat',
    drainage: 'Good',
    distPavedRoad: '5',
    distMarket: '10',
    crops: [
      { id: '1', type: 'Maize', yieldLast: '1000', yieldUnit: 'kg', area: '1', productionPurpose: [] },
      { id: '2', type: 'Cassava', yieldLast: '500', yieldUnit: 'kg', area: '0.5', productionPurpose: [] },
    ],
    livestock: { kept: false, types: [], details: {}, cropIntegration: false },
    specialized: { other: '' },
    soilWater: {
      fertilizerUseEver: true,
      fertilizerUseThisSeason: true,
      fertilizerTypes: ['UREA'],
      fertilizerAffordability: '',
      pesticideUse: false,
      pesticideTypes: [],
      organicMatter: [],
      soilConservation: [],
      soilTestHistory: 'Never',
    },
    soilSamples: { collected: false, count: '0', samples: [] },
    inputs: { seedSource: [], improvedSeeds: '', laborType: [], mechanization: [] },
    postHarvest: { hasStorage: false, storageType: [], losses: '', lossCauses: [], processing: [] },
    marketing: {
      marketName: '',
      distMarket: '',
      transport: [],
      sellingTiming: [],
      priceSetter: '',
      satisfaction: '',
      challenges: [],
      contractFarming: false,
      contractType: [],
    },
    finance: {
      hasBankAccount: false,
      mobileMoneyUse: true,
      creditAccess: false,
      insurance: false,
      savingsGroup: false,
    },
    extension: {
      accessLastYear: true,
      source: [],
      infoSources: [],
      smartphone: true,
      digitalInterest: 'INTERESTED',
      weatherAccess: false,
    },
    challenges: {
      mainChallenges: [],
      futurePlan: '',
      youthInterest: '',
      climateAwareness: true,
      climateAdaptation: [],
      supportNeeded: '',
      comments: '',
    },
    media: { extraPhotos: [] },
    finalNotes: {
      observations: '',
      dataQuality: 'GOOD',
      duration: '30',
    },
    certification: {
      auditorName: 'Grace Kimaro',
      submissionTime: new Date().toISOString(),
      consents: {
        data: true,
        gps: true,
        photos: true,
        soil: true,
        farmer: true,
        phone: true,
      },
    },
  },
};

/** Invalid: only 3 corners */
export const INVALID_FARM_AUDIT: AuditRecord = {
  ...VALID_FARM_AUDIT,
  id: 'test-audit-invalid',
  farmData: {
    ...VALID_FARM_AUDIT.farmData!,
    boundaryCorners: TEST_CORNERS.slice(0, 3),
  },
};

/** Poor GPS accuracy: all corners >50m */
export const POOR_GPS_CORNERS: BoundaryCorner[] = TEST_CORNERS.map((c) => ({
  ...c,
  accuracy: 75,
}));
